### ISSUE TITLE
Anytime i try set CHANNEL_LAYERS i get this exception

### ISSUE THREAD

**Issue by waqasraz** [andrewgodwin/channels#101]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7ff45a7bf8>
Traceback (most recent call last):
  File "/home/waqas/testing/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/waqas/testing/lib/python3.4/site-packages/channels/management/commands/runserver.py", line 37, in inner_run
    self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
  File "/home/waqas/testing/lib/python3.4/site-packages/channels/asgi.py", line 53, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/home/waqas/testing/lib/python3.4/site-packages/channels/asgi.py", line 48, in make_backend
    routing=routing,
  File "/home/waqas/testing/lib/python3.4/site-packages/channels/asgi.py", line 70, in __init__
    self.router = Router(self.routing)
  File "/home/waqas/testing/lib/python3.4/site-packages/channels/routing.py", line 27, in __init__
    self.routing.extend(entry.expand_routes())
AttributeError: 'str' object has no attribute 'expand_routes'

I've tried both BACKENDS same error. here is how I am setting it

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "testproject.urls.channel_routing",
        "CONFIG": {
           "hosts": [("localhost", 6379)],
        }
    },
}

**Comment by andrewgodwin** [comment]
What does your `channel_routing` look like? The error seems to indicate you have a string in there rather than a `route()` - there should be a nicer error if so.

**Comment by waqasraz** [comment]
Yes, that is exactly the problem. I was using 

"websocket.receive": consumers.ws_message,

insted of route("websocket.receive": consumers.ws_message,)

**Comment by andrewgodwin** [comment]
OK, I'll update the code to show a nicer error in that case.
