### ISSUE TITLE
Eventual KeyError on websocket connect

### ISSUE THREAD

**Issue by nunesvictor** [andrewgodwin/channels#199]
Hi,

I'm having some trouble with a simple consumer. Sometimes it raises a KeyError when I try to access a channel_session data. Have a look:

## consumers.py

```
from channels import Channel, Group
from channels.sessions import channel_session

def message_consumer(message):
    Group("chamado-%s" % message.content['chamado']).send({
        "text": message.content['message'],
    })

@channel_session
def ws_connect(message, chamado):
    message.channel_session['chamado'] = chamado
    Group("chamado-%s" % chamado).add(message.reply_channel)


@channel_session
def ws_message(message):
    Channel("channel-chamados").send({
        "chamado": message.channel_session['chamado'],
        "message": message['text'],
    })



@channel_session
def ws_disconnect(message):
    Group("chamado-%s" % message.channel_session['chamado']).discard(
        message.reply_channel
    )
```

## routering.py

```
from chamados.consumers import (
    message_consumer,
    ws_connect,
    ws_disconnect,
    ws_message
)
from channels.routing import include, route

chamado_routing = [
    route("websocket.connect", ws_connect, path=r"^/detail/(?P<chamado>\d+)/$"),
    route("websocket.disconnect", ws_disconnect),
    route("websocket.receive", ws_message),
]


channel_routing = [
    route("channel-chamados", message_consumer),
    include(chamado_routing, path=r"^/chamados"),
]
```

## settings.py

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
        "ROUTING": "helpdesk.routing.channel_routing",
    },
}
```

## websocket.js

```
$(function() {
    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
    var websock = new WebSocket(ws_scheme + '://' + window.location.host + window.location.pathname);

    websock.onmessage = function(event) {
        console.log(event.data);
    };

    websock.onopen = function(event) {
        websock.send('Hello world');
    };
});
```

First load works like charm, but when I load the same page in another browser windows it brokes with this message:

```
2016-06-06 16:35:56,261 - ERROR - worker - Error processing message with consumer chamados.consumers.ws_message:
Traceback (most recent call last):
  File "/home/nunesvictor/dev/helpdesk/.env/local/lib/python2.7/site-packages/channels/worker.py", line 107, in run
    consumer(message, **kwargs)
  File "/home/nunesvictor/dev/helpdesk/.env/local/lib/python2.7/site-packages/channels/sessions.py", line 64, in inner
    return func(message, *args, **kwargs)
  File "/home/nunesvictor/dev/helpdesk/src/chamados/consumers.py", line 27, in ws_message
    "chamado": message.channel_session['chamado'],
  File "/home/nunesvictor/dev/helpdesk/.env/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'chamado'
```

I can't figure why this keeps happening if I always set the message.channel_session['chamado'] on the ws_connect, is this a bug or just me being a noob?

**Comment by andrewgodwin** [comment]
You're running into race conditions with the `receive` handler being run before the `connect` handler has finished working. You'll want to drop the `enforce_ordering` decorator on the two functions, probably in `slight` mode; see here: http://channels.readthedocs.io/en/latest/getting-started.html#enforcing-ordering

**Comment by nunesvictor** [comment]
That worked! Thank you for you really quick and helpful response. Now I can add django-channels on my project for sure.

Keep doing your awesome job!
