### ISSUE TITLE
redis.exceptions.ConnectionError: Error 99 connecting to 127.0.0.1:6379. Cannot assign requested address

### ISSUE THREAD

**Issue by new-player** [andrewgodwin/channels#219]
Find the stack below. I was following this tutorial: https://blog.heroku.com/archives/2016/3/17/in_deep_with_django_channels_the_future_of_real_time_apps_in_django

2016-06-25 11:48:43,317 - INFO - runworker - Running worker against channel layer default (asgi_redis.RedisChannelLayer)
2016-06-25 11:48:43,318 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/channels/management/commands/runworker.py", line 54, in handle
    exclude_channels=options.get("exclude_channels", None),
  File "/usr/local/lib/python2.7/dist-packages/channels/worker.py", line 78, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/local/lib/python2.7/dist-packages/asgi_redis.py", line 110, in receive_many
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1146, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 570, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to 127.0.0.1:6379. Cannot assign requested address.

**Comment by new-player** [comment]
I got this after running daphne.

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1662, in lineReceived
    request = self.requestFactory(self, len(self.requests))
  File "/usr/local/lib/python2.7/dist-packages/daphne/http_protocol.py", line 50, in __init__
    self.reply_channel = self.factory.channel_layer.new_channel("http.response!")
  File "/usr/local/lib/python2.7/dist-packages/asgi_redis.py", line 139, in new_channel
    if not connection.exists(key):
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 838, in exists
    return self.execute_command('EXISTS', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 570, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to 127.0.0.1:6379. Cannot assign requested address.

**Comment by andrewgodwin** [comment]
This is a problem with your system/kernel socket setup, not Daphne - you've likely run out of ephemeral ports on your system. Try closing down some other processes that might be using sockets or swapping the install onto a fresh server.

**Comment by new-player** [comment]
Issue was older version of asgi_redis package. Thanks anyways.
