### ISSUE TITLE
Error in python3

### ISSUE THREAD

**Issue by freakypie** [andrewgodwin/channels#22]
```
Traceback (most recent call last):
  File ".../lib/python3.4/site-packages/channels/worker.py", line 34, in run
    consumer(message)
  File ".../lib/python3.4/site-packages/channels/decorators.py", line 54, in inner
    session_key = "skt" + hashlib.md5(reply_name[:-24]).hexdigest()[:8] + reply_name[-24:]
TypeError: Unicode-objects must be encoded before hashing
```

I'll try to send a merge request for you

**Comment by andrewgodwin** [comment]
Fixed in cac848fc8924d79584ff21a3f10ae4b388870899.
