### ISSUE TITLE
Ptyhon 3 compatibility error with RedisBackend

### ISSUE THREAD

**Issue by EliotBerriot** [andrewgodwin/channels#24]
Using the Redis backend with Python 3 seems to break `channels`. My project is set up as follows:

```python
CHANNEL_BACKENDS = {
    "default": {
        "BACKEND": "channels.backends.redis_py.RedisChannelBackend",
        "HOST": "localhost",
        "ROUTING": "project.routing.channel_routing",
    },
}
```

Trying to access any page via HTTP raises the following error:

    Stacktrace 
        Traceback (most recent call last):
          File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
            self.result = application(self.environ, self.start_response)
          File "/home/user/.local/share/virtualenvs/project/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
            return self.application(environ, start_response)
          File "/home/user/.local/share/virtualenvs/project/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
            response = self.get_response(request)
          File "/home/user/.local/share/virtualenvs/project/lib/python3.4/site-packages/channels/interfaces/wsgi.py", line 19, in get_response
            Channel("http.request", channel_backend=self.channel_backend).send(request.channel_encode())
          File "/home/user/.local/share/virtualenvs/project/lib/python3.4/site-packages/channels/channel.py", line 35, in send
            self.channel_backend.send(self.name, content)
          File "/home/user/.local/share/virtualenvs/project/lib/python3.4/site-packages/channels/backends/redis_py.py", line 31, in send
            key = self.prefix + uuid.uuid4().get_hex()
        AttributeError: 'UUID' object has no attribute 'get_hex'

A dumb search for that error [shows me](https://github.com/agrover/rtslib-fb/issues/52) it's probably a Python 2/3 compat issue, and 
replacing `get_hex()` with `hex` should solve the problem.

Also, I wanted to thank you for the quality of this project : I tried to integrate it on one of my project and it works exactly as shown in the docs. I really like your approach to solve this problem and even if I probably won't use it in production until it's ready, it's nice to know there is a clean solution around that support WebSockets directly in Django.

**Comment by andrewgodwin** [comment]
Sorry about that! Fixed in cac848fc8924d79584ff21a3f10ae4b388870899.
