### ISSUE TITLE
Its impossible to declare GenericConsumer without path - KeyError path

### ISSUE THREAD

**Issue by michaelkuty** [andrewgodwin/channels#241]
from .consumers FrontendEditConsumer
	from channels import route_class

	channel_routing = [
	    route_class(FrontendEditConsumer),
	]

    2016-07-11 06:54:01,636 - ERROR - worker - Error processing message with consumer leonardo.module.web.widgets.consumers.FrontendEditConsumer:
    Traceback (most recent call last):
      File "/Users/michaelkuty/projects/leonardo-dev/leonardo_venv/lib/python2.7/site-packages/channels/worker.py", line 107, in run
        consumer(message, **kwargs)
      File "/Users/michaelkuty/projects/leonardo-dev/leonardo_venv/lib/python2.7/site-packages/channels/generic/base.py", line 30, in __init__
        self.dispatch(message, **kwargs)
      File "/Users/michaelkuty/projects/leonardo-dev/leonardo_venv/lib/python2.7/site-packages/channels/generic/base.py", line 56, in dispatch
        return self.get_handler(message, **kwargs)(message, **kwargs)
      File "/Users/michaelkuty/projects/leonardo-dev/leonardo_venv/lib/python2.7/site-packages/channels/generic/websockets.py", line 30, in get_handler
        self.path = message['path']
      File "/Users/michaelkuty/projects/leonardo-dev/leonardo_venv/lib/python2.7/site-packages/channels/message.py", line 32, in __getitem__
        return self.content[key]
    KeyError: 'path'

it is possible to use GenericConsumer without path or path is required ?

standard route without path works, therefore, I would assume the same functionality for generic consumers

**Comment by andrewgodwin** [comment]
The bug here is that it expects every message to have a `path` key, which is a bug - I will fix it tonight.

**Comment by andrewgodwin** [comment]
On second inspection, this is on the WebSocket generic consumer, which always expects a path on messages as all WS ones have them. Are you manually trying to pass messages into the websocket connect/receive channels?

If not, turn on debug logging with `-v 2` and see what channel the consumer is running on (that will print the incoming channel name before running consumers)

**Comment by michaelkuty** [comment]
Yes, as you say when I send the message path must be specified.
Thanks for your time !

**Comment by michaelkuty** [comment]
Maybe would be good to have mentioned in documentation
