### ISSUE TITLE
don't work with allauth 

### ISSUE THREAD

**Issue by x007007007** [andrewgodwin/channels#265]
setting.py like this

```
SITE_ID = 1
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'pulsar.apps.pulse',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.gitlab',
    'allauth.socialaccount.providers.bitbucket',
    'channels',
]



MIDDLEWARE_CLASSES = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend"

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

## CHANNEL

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
        },
        "ROUTING": "deltamiao.routing.channel_routing",
    },
}

```
when i runserver ,it have error:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10b19fd08>
Traceback (most recent call last):
  File "/Users/xxc/.virtualenvs/py3/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/xxc/.virtualenvs/py3/lib/python3.5/site-packages/channels-0.17.1-py3.5.egg/channels/management/commands/runserver.py", line 40, in inner_run
    http_consumer=self.get_consumer(*args, **options),
  File "/Users/xxc/.virtualenvs/py3/lib/python3.5/site-packages/channels-0.17.1-py3.5.egg/channels/management/commands/runserver.py", line 134, in get_consumer
    return StaticFilesConsumer()
  File "/Users/xxc/.virtualenvs/py3/lib/python3.5/site-packages/channels-0.17.1-py3.5.egg/channels/handler.py", line 331, in __init__
    self.handler = self.handler_class()
  File "/Users/xxc/.virtualenvs/py3/lib/python3.5/site-packages/channels-0.17.1-py3.5.egg/channels/staticfiles.py", line 18, in __init__
    super(StaticFilesHandler, self).__init__()
  File "/Users/xxc/.virtualenvs/py3/lib/python3.5/site-packages/channels-0.17.1-py3.5.egg/channels/handler.py", line 178, in __init__
    self.load_middleware()
  File "/Users/xxc/.virtualenvs/py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 51, in load_middleware
    mw_class = import_string(middleware_path)
  File "/Users/xxc/.virtualenvs/py3/lib/python3.5/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/Users/xxc/.virtualenvs/py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ImportError: No module named 'allauth.account.auth_backends.AuthenticationBackenddjango'; 'allauth.account.auth_backends' is not a package
```

**Comment by x007007007** [comment]
when i change MIDDLEWARE_CLASSES it work 

```
MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend"
]

```
