### ISSUE TITLE
Compatibility with django 1.6

### ISSUE THREAD

**Issue by inf430** [andrewgodwin/channels#277]
Hi,

I use django channel with django 1.9.8 without any porblem. but I can't with django 1.6. As a matter of fact I tried but got this error : 

Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Python27\lib\site-packages\channels\management\commands\runserver.py", line 11, in <module>
    from channels import DEFAULT_CHANNEL_LAYER, channel_layers
ImportError: cannot import name channel_layers

Is it possible to run django channel with django 1.6 ? 
What should I do to get it run with django 1.6?

**Comment by andrewgodwin** [comment]
I'm afraid Channels only supports Django 1.8 and higher.

**Comment by inf430** [comment]
I'm stuck!

I'm working on a project running under django 1.6 and my job is add a chat
app; Do you have and advice for me please?

Thanks

2016-08-01 10:45 GMT+02:00 Andrew Godwin <notifications@github.com>:

**Comment by AlexejStukov** [comment]
You could use [swampdragon](https://github.com/jonashagstedt/swampdragon), but the owner has no time to support it anymore. There is an [example](https://github.com/jonashagstedt/swampdragon/tree/master/chat_example) for a simple chat client that you can expand on.

**Comment by FZambia** [comment]
@inf430 you could also use [Centrifugo](https://github.com/centrifugal/centrifugo) - it's a real-time server independent from framework, we have projects with chats that still powered by Django 1.4.X

**Comment by KhasanovBI** [comment]
You could also use [Crossbar.io](http://crossbar.io/).

**Comment by inf430** [comment]
Thanks !

I'll give them a try.

2016-08-01 16:35 GMT+02:00 Хасанов Булат <notifications@github.com>:
