### ISSUE TITLE
Illegals characters group name ?

### ISSUE THREAD

**Issue by yaslim** [andrewgodwin/channels#335]
Hello,

I try to create group names with these characters : é,é,ê,ë,@,?,!...

But I have a error : 

`2016-09-02 15:38:58,928 - ERROR - worker - Error processing message with consumer channels.auth.inner:
Traceback (most recent call last):
  File "/home/project/channels/worker.py", line 111, in run
    consumer(message, **kwargs)
  File "/home/project/channels/sessions.py", line 180, in inner
    result = func(message, *args, **kwargs)
  File "/home/project/channels/auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "/home/project/channels/sessions.py", line 64, in inner
    return func(message, *args, **kwargs)
  File "/home/project/channels/auth.py", line 88, in inner
    return func(message, *args, **kwargs)
  File "/home/project/main_app/consumers.py", line 65, in ws_connect
    Group(u"\xe9").add(message.reply_channel)
  File "/home/project/channels/channel.py", line 62, in add
    self.channel_layer.group_add(self.name, channel)
  File "/usr/local/lib/python2.7/dist-packages/asgi_redis/core.py", line 166, in group_add
    assert self.valid_group_name(group), "Group name not valid"
AssertionError: Group name not valid`

**So How can I do ?
What are the illegals characters from group names ?**

Thank you

**Comment by andrewgodwin** [comment]
Please see #336 for more details, but it's basically a-z, A-Z, -, _ and .
