### ISSUE TITLE
Error response when using django login - Using channels 0.8

### ISSUE THREAD

**Issue by jaganra** [andrewgodwin/channels#70]
Error processing message with consumer <channels.adapters.UrlConsumer object at 0x7f9d09c81f10>:
Traceback (most recent call last):
  File "/home/yyy/xxx/local/lib/python2.7/site-packages/channels/worker.py", line 34, in run
    consumer(message)
  File "/home/yyy/xxx/local/lib/python2.7/site-packages/channels/adapters.py", line 24, in __call__
    message.reply_channel.send(response.channel_encode())
  File "/home/yyy/xxx/local/lib/python2.7/site-packages/channels/response.py", line 11, in encode_response
    "content": response.content,
  File "/home/yyy/xxx/local/lib/python2.7/site-packages/django/http/response.py", line 409, in content
    "Use `streaming_content` instead." % self.__class__.__name__)
AttributeError: This FileResponse instance has no `content` attribute. Use `streaming_content` instead.

**Comment by jaganra-ubnt** [comment]
This seems to happen with Django template views.

**Comment by andrewgodwin** [comment]
This is fixed in the most recent release.
