### ISSUE TITLE
IndexError: deque index out of range

### ISSUE THREAD

**Issue by Charlex** [andrewgodwin/channels#78]
According to [this similar thread](https://github.com/myano/jenni/issues/159), this issue might be an "inherent issue with multi-threading." So I'm not sure if it requires attention, but I figured it might be good to put on the radar.

```
[2016/03/03 17:04:54] WebSocket CONNECT /liveblog [127.0.0.1:62988]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/cbodkin/.virtualenvs/p2p-liveblog/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 151, in run
    worker.run()
  File "/Users/cbodkin/.virtualenvs/p2p-liveblog/lib/python2.7/site-packages/channels/worker.py", line 29, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/Users/cbodkin/.virtualenvs/p2p-liveblog/lib/python2.7/site-packages/asgiref/inmemory.py", line 47, in receive_many
    self._clean_expired()
  File "/Users/cbodkin/.virtualenvs/p2p-liveblog/lib/python2.7/site-packages/asgiref/inmemory.py", line 109, in _clean_expired
    while queue and queue[0][0] < time.time():
IndexError: deque index out of range
```

**Comment by andrewgodwin** [comment]
Hmm, interesting, that backend is meant to have threading locks to prevent that. What version of `asgiref` do you have installed?

**Comment by Charlex** [comment]
Pip is telling me I have 0.9 installed.

**Comment by andrewgodwin** [comment]
Oh, my bad, I had those changes locally and hadn't pushed them since I wrote them on a plane. Install `asgiref` 0.9.1 and it should fix it.

**Comment by Charlex** [comment]
Oh, thanks! It happened sporadically, but I'll let you know if I run into again.

**Comment by andrewgodwin** [comment]
Yup, like most threading errors, it's sporadic - I found it during websocket load testing. I'll close this for now, reopen if it happens again.

**Comment by Charlex** [comment]
Sounds good.
