### ISSUE TITLE
Exception on runserver - default configuration

### ISSUE THREAD

**Issue by orokusaki** [andrewgodwin/channels#85]
I'm getting the following with `runserver`:

    Traceback (most recent call last):
      File "/Users/mva/.virtualenvs/spam/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
        fn(*args, **kwargs)
      File "/Users/mva/.virtualenvs/spam/lib/python3.5/site-packages/channels/management/commands/runserver.py", line 37, in inner_run
        self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
      File "/Users/mva/.virtualenvs/spam/lib/python3.5/site-packages/channels/asgi.py", line 53, in __getitem__
        self.backends[key] = self.make_backend(key)
      File "/Users/mva/.virtualenvs/spam/lib/python3.5/site-packages/channels/asgi.py", line 33, in make_backend
        raise InvalidChannelLayerError("No BACKEND specified for %s" % name)
    channels.asgi.InvalidChannelLayerError: No BACKEND specified for default

I was reading http://channels.readthedocs.org/en/latest/getting-started.html#first-consumers where it mentions that, by default, Channels effectively delegates to Django via WSGI.

### Environment

  - Python 3.5.1
  - django==1.9.4
  - channels==0.9.4

**Comment by andrewgodwin** [comment]
Ah yes, the delegation code for you-installed-channels-but-want-old-runserver was removed a while back. Let me fix that...

**Comment by andrewgodwin** [comment]
Fixed in channels 0.9.5.

**Comment by orokusaki** [comment]
Wow... that was some epic timing. Thanks for the lightning patch, @andrewgodwin!
