### ISSUE TITLE
"path" regex doesn't accept strings on Python 3

### ISSUE THREAD

**Issue by ulope** [andrewgodwin/channels#93]
Using a string for the `path` regex argument to `route()` under Python leads to the following exception:

```
Traceback (most recent call last):
  File "/Users/ulo/.pythonz/pythons/CPython-3.4.3/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/Users/ulo/Envs/dali/lib/python3.4/site-packages/channels/management/commands/runserver.py", line 152, in run
    worker.run()
  File "/Users/ulo/Envs/dali/lib/python3.4/site-packages/channels/worker.py", line 69, in run
    match = self.channel_layer.router.match(message)
  File "/Users/ulo/Envs/dali/lib/python3.4/site-packages/channels/routing.py", line 50, in match
    match = route.match(message)
  File "/Users/ulo/Envs/dali/lib/python3.4/site-packages/channels/routing.py", line 133, in match
    match = re.match(value, message[name])
  File "/Users/ulo/Envs/dali/lib/python3.4/re.py", line 160, in match
    return _compile(pattern, flags).match(string)
TypeError: can't use a string pattern on a bytes-like object
```

Changing the value of `path` to `bytes` appears to fix the problem.

Edit: This also leads to any captured keyword arguments becoming bytes as well.

Versions used:
* Python 3.4.3
* django 1.9.4
* channels 0.10.0
* asgi-redis 0.9.0

**Comment by andrewgodwin** [comment]
Fix for this is now released in channels 0.10.1.
